# Generated by Django 2.2.2 on 2019-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('site', models.URLField()),
                ('desc', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
